using System.Text;

namespace EHR.Helpers;

/// <summary>
/// Encrypts and decrypts the PHI columns of a DME customer record, and builds
/// the search tokens that make encrypted names findable.
///
/// WHY THIS EXISTS
/// Clinical patient records in this database are AES-GCM encrypted at rest:
/// Patients.FirstName reads as DmBmQNKaUVRaaB1o7QQ9fKkpv. DME customer records
/// were plaintext, so the same person's name, address, phone and SSN fragment
/// sat in the clear in DmeCustomers while being ciphertext in Patients. A DME
/// customer is a patient by any HIPAA definition; the storage should not depend
/// on which product created the row.
///
/// WHY IT IS A SEPARATE CLASS FROM EncryptionHelper
/// EncryptionHelper owns the cryptography (keys, AES-GCM, the HMAC used for
/// search hashing) and is shared with the clinical side. This class owns one
/// question only: WHICH DME columns are PHI and how a customer row is turned
/// into search tokens. Keeping the two apart means the DME product never grows
/// its own crypto, and the field list lives in exactly one place instead of
/// being restated at every call site that reads or writes a customer.
///
/// SEARCH OVER ENCRYPTED DATA
/// A LIKE '%smith%' cannot work against ciphertext. This uses the same blind
/// index approach the clinical side already uses (BlindIndexService): hash every
/// prefix of a normalised value with a keyed HMAC and store the hashes. Looking
/// up "mar" hashes the query the same way and matches Margaret, without the
/// database ever holding a searchable copy of the name.
///
/// The tradeoff is honest and worth stating: prefix search still works, but
/// mid-word search ("argaret") does not. That is inherent to blind indexing,
/// not an implementation shortcut.
///
/// WHO CALLS IT
/// DmeController, on customer create and on customer read/search.
/// </summary>
public sealed class DmeCustomerPhi
{
    private readonly EncryptionHelper _crypto;

    public DmeCustomerPhi(EncryptionHelper crypto) => _crypto = crypto;

    /// <summary>
    /// DmeCustomers columns holding PHI. Mirrors the clinical Patient field list
    /// in EncryptionConfiguration so the two products protect the same things.
    ///
    /// Dob is NOT here: it is a DATE column and the clinical side does not
    /// encrypt DateOfBirth either. Changing the column type is a separate piece
    /// of work with its own migration, and doing half of it would be worse than
    /// doing none. Flagged rather than quietly skipped.
    ///
    /// AccountNo is NOT here: it is the internal handle the UI and staff use to
    /// find a record, it is generated by us rather than derived from the person,
    /// and the clinical side leaves the equivalent identifier in the clear.
    /// </summary>
    public static readonly string[] EncryptedColumns =
    {
        "FirstName", "LastName", "Phone", "Email",
        "AddressLine1", "City", "State", "Zip",
        "EmergencyName", "EmergencyRel", "EmergencyPhone",
        "SsnLast4",
    };

    /// <summary>Shortest prefix indexed. 1 so a single initial still matches.</summary>
    private const int MinPrefixLength = 1;

    /// <summary>
    /// Longest prefix indexed. Matches BlindIndexService so both products
    /// behave the same. Beyond this the search narrows client-side.
    /// </summary>
    private const int MaxPrefixLength = 15;

    /// <summary>Encrypt one value. Null and empty pass through untouched.</summary>
    public string? Encrypt(string? plain) => _crypto.Encrypt(plain);

    /// <summary>
    /// True when the value is already ciphertext.
    ///
    /// Needed by the backfill. Encrypting an already-encrypted value would
    /// double-encrypt it, and because Decrypt returns its input unchanged when
    /// decryption fails, that damage is silent: the column would still read
    /// back as a plausible string, just the wrong one. Checking first is what
    /// makes re-running the backfill safe.
    /// </summary>
    public bool IsEncrypted(string? value) => _crypto.IsEncrypted(value);

    /// <summary>
    /// Decrypt every PHI column of a customer row in place.
    ///
    /// Safe on rows that are still plaintext: EncryptionHelper.Decrypt returns
    /// the input unchanged when it is not valid ciphertext. That is what lets
    /// encryption roll out without a flag day, and what makes a partially
    /// backfilled table readable.
    /// </summary>
    public void DecryptRow(Dictionary<string, object?>? row)
    {
        if (row == null) return;

        foreach (var column in EncryptedColumns)
        {
            if (!row.TryGetValue(column, out var value)) continue;
            if (value is not string s || s.Length == 0) continue;
            row[column] = _crypto.Decrypt(s);
        }
    }

    /// <summary>Decrypt a whole result set.</summary>
    public void DecryptRows(IEnumerable<Dictionary<string, object?>> rows)
    {
        foreach (var row in rows) DecryptRow(row);
    }

    /// <summary>
    /// Turn the CustomerFirstName / CustomerLastName columns that vDmeOrders and
    /// vDmeRentals return into a decrypted CustomerName the views can render.
    ///
    /// WHY THE VIEWS DO NOT JUST CONCATENATE
    /// Two AES-GCM ciphertexts joined with a space in SQL are not decryptable as
    /// one value. The database has no key and no business having one, so the
    /// join has to happen after decryption, here. Skipping this step does not
    /// throw: the screen simply renders base64, which is how it was caught.
    ///
    /// A row that already carries a CustomerName (the claim screens, where the
    /// name is stored as filed rather than joined) is decrypted in place instead.
    /// </summary>
    public void ComposeCustomerNames(IEnumerable<Dictionary<string, object?>> rows)
    {
        foreach (var row in rows) ComposeCustomerName(row);
    }

    /// <inheritdoc cref="ComposeCustomerNames"/>
    public void ComposeCustomerName(Dictionary<string, object?>? row)
    {
        if (row == null) return;

        if (row.ContainsKey("CustomerFirstName") || row.ContainsKey("CustomerLastName"))
        {
            var first = Decrypt(row.TryGetValue("CustomerFirstName", out var f) ? f as string : null);
            var last = Decrypt(row.TryGetValue("CustomerLastName", out var l) ? l as string : null);
            row["CustomerName"] = $"{first} {last}".Trim();
            return;
        }

        if (row.TryGetValue("CustomerName", out var stored) && stored is string s && s.Length > 0)
        {
            row["CustomerName"] = _crypto.Decrypt(s);
        }
    }

    /// <summary>Decrypt one value, passing null, empty and plaintext through.</summary>
    public string? Decrypt(string? value)
        => string.IsNullOrEmpty(value) ? value : _crypto.Decrypt(value);

    /// <summary>
    /// Hash a search term the same way the stored tokens were hashed, so the
    /// query can be matched without decrypting anything.
    /// </summary>
    public string? SearchHash(string term)
    {
        var normalised = Normalise(term);
        if (normalised.Length == 0) return null;
        if (normalised.Length > MaxPrefixLength) normalised = normalised[..MaxPrefixLength];
        return _crypto.GenerateSearchHash(normalised);
    }

    /// <summary>
    /// Build the blind index tokens for one customer: every prefix of each
    /// searchable field, hashed.
    ///
    /// Phone is indexed digits-only so "(214) 555-0101" is found by "2145550101"
    /// and by "214", which is how people actually search for a phone number.
    /// </summary>
    public List<(string hash, string fieldType, int prefixLength)> BuildSearchTokens(
        string? firstName, string? lastName, string? phone)
    {
        var tokens = new List<(string, string, int)>();

        AddPrefixes(tokens, firstName, "FirstName");
        AddPrefixes(tokens, lastName, "LastName");

        // Both orderings, so "margaret ellis" and "ellis margaret" both match.
        if (!string.IsNullOrWhiteSpace(firstName) && !string.IsNullOrWhiteSpace(lastName))
        {
            AddPrefixes(tokens, $"{firstName} {lastName}", "FullName");
            AddPrefixes(tokens, $"{lastName} {firstName}", "FullName");
        }

        if (!string.IsNullOrWhiteSpace(phone))
        {
            var digits = new string(phone.Where(char.IsDigit).ToArray());
            AddPrefixes(tokens, digits, "Phone");
        }

        // The same prefix can arrive from more than one field; store it once.
        return tokens
            .GroupBy(t => new { t.Item1, t.Item2 })
            .Select(g => g.First())
            .ToList();
    }

    private void AddPrefixes(List<(string, string, int)> tokens, string? value, string fieldType)
    {
        var normalised = Normalise(value ?? "");
        if (normalised.Length == 0) return;

        var max = Math.Min(normalised.Length, MaxPrefixLength);
        for (int i = MinPrefixLength; i <= max; i++)
        {
            var hash = _crypto.GenerateSearchHash(normalised[..i]);
            if (!string.IsNullOrEmpty(hash)) tokens.Add((hash!, fieldType, i));
        }
    }

    /// <summary>
    /// Lowercase, trim, and drop the punctuation people leave out when
    /// searching, so "O'Brien" is found by "obrien" and "(214) 555-0101" by
    /// "2145550101". Must stay identical to the normalisation used when the
    /// tokens were built, or nothing matches.
    /// </summary>
    private static string Normalise(string value)
    {
        if (string.IsNullOrEmpty(value)) return string.Empty;

        var sb = new StringBuilder(value.Length);
        foreach (var c in value.ToLowerInvariant().Trim())
        {
            if (char.IsLetterOrDigit(c) || c == ' ' || c == '@' || c == '.') sb.Append(c);
        }
        return sb.ToString();
    }
}
