-- ============================================================================
-- Migration 026: Schema sync — fill the gap between code/production and
--                Manual migration files
-- ============================================================================
-- The Manual/ migration folder is incomplete: 56 columns and 5 tables that
-- exist in production (per ServerImEhrSchema.sql 2026-04-27) and are referenced
-- by EF Core entities have no corresponding migration script. Multiple API
-- endpoints throw SqlException 207 ("Invalid column/object name") on a fresh DB.
--
-- Generated by schema-diff.py against ServerImEhrSchema.sql.
-- All ALTER ADD statements are NULL-safe (no NOT NULL on existing tables).
-- All CREATE TABLE statements are guarded by IF OBJECT_ID(...) IS NULL.
--
-- Run with:
--   sqlcmd -S localhost -d IMEHR -E -I -i migration_026_schema_sync.sql
--
-- Idempotent — safe to re-run.
-- ============================================================================

SET QUOTED_IDENTIFIER ON;
SET ANSI_NULLS ON;
GO

-- ----------------------------------------------------------------------------
-- Missing columns (existing tables)
-- ----------------------------------------------------------------------------

IF COL_LENGTH('dbo.Appointments', 'TelehealthToken') IS NULL ALTER TABLE dbo.[Appointments] ADD [TelehealthToken] [nvarchar](max) NULL;

IF COL_LENGTH('dbo.BillingClaims', 'ClinicalNoteId') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [ClinicalNoteId] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'AppointmentId') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [AppointmentId] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'CareEpisodeId') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [CareEpisodeId] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'AuthorizationId') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [AuthorizationId] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'ProviderId') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [ProviderId] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'LocationId') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [LocationId] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuranceTypeCode') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuranceTypeCode] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'PatientSignatureOnFile') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [PatientSignatureOnFile] [bit] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredSignatureOnFile') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredSignatureOnFile] [bit] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'ReferringProviderName') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [ReferringProviderName] [nvarchar](200) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'ReferringProviderNpi') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [ReferringProviderNpi] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'DiagnosisCodes') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [DiagnosisCodes] [nvarchar](max) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'PriorAuthorizationNumber') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [PriorAuthorizationNumber] [nvarchar](100) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'PlaceOfServiceCode') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [PlaceOfServiceCode] [nvarchar](10) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'FederalTaxId') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [FederalTaxId] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'PatientAccountNumber') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [PatientAccountNumber] [nvarchar](50) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'AcceptAssignment') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [AcceptAssignment] [bit] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'AmountPaid') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [AmountPaid] [decimal](10, 2) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'RenderingProviderName') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [RenderingProviderName] [nvarchar](200) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'RenderingProviderNpi') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [RenderingProviderNpi] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'FacilityName') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [FacilityName] [nvarchar](200) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'FacilityAddress') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [FacilityAddress] [nvarchar](500) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'FacilityNpi') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [FacilityNpi] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'BillingProviderName') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [BillingProviderName] [nvarchar](200) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'BillingProviderAddress') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [BillingProviderAddress] [nvarchar](500) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'BillingProviderNpi') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [BillingProviderNpi] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'BillingProviderTaxonomy') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [BillingProviderTaxonomy] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredName') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredName] [nvarchar](200) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredAddress') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredAddress] [nvarchar](500) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredCity') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredCity] [nvarchar](100) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredState') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredState] [nvarchar](10) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredZip') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredZip] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredDob') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredDob] [date] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredGender') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredGender] [nvarchar](10) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredPolicyNumber') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredPolicyNumber] [nvarchar](50) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'InsuredGroupNumber') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [InsuredGroupNumber] [nvarchar](50) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'SubscriberRelationship') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [SubscriberRelationship] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'TypeOfBill') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [TypeOfBill] [nvarchar](10) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'AdmissionDate') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [AdmissionDate] [date] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'AdmissionType') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [AdmissionType] [int] NULL;
IF COL_LENGTH('dbo.BillingClaims', 'PatientDischargeStatus') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [PatientDischargeStatus] [nvarchar](10) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'ConditionCodes') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [ConditionCodes] [nvarchar](max) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'ValueCodes') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [ValueCodes] [nvarchar](max) NULL;
IF COL_LENGTH('dbo.BillingClaims', 'OccurrenceCodes') IS NULL ALTER TABLE dbo.[BillingClaims] ADD [OccurrenceCodes] [nvarchar](max) NULL;

IF COL_LENGTH('dbo.CareEpisodes', 'ReferringProviderNpi') IS NULL ALTER TABLE dbo.[CareEpisodes] ADD [ReferringProviderNpi] [nvarchar](20) NULL;
IF COL_LENGTH('dbo.Charges', 'RevenueCode') IS NULL ALTER TABLE dbo.[Charges] ADD [RevenueCode] [nvarchar](10) NULL;

IF COL_LENGTH('dbo.Insurances', 'SubscriberFirstName') IS NULL ALTER TABLE dbo.[Insurances] ADD [SubscriberFirstName] [nvarchar](100) NULL;
IF COL_LENGTH('dbo.Insurances', 'SubscriberLastName') IS NULL ALTER TABLE dbo.[Insurances] ADD [SubscriberLastName] [nvarchar](100) NULL;

IF COL_LENGTH('dbo.PatientConversations', 'UserUnreadCount') IS NULL ALTER TABLE dbo.[PatientConversations] ADD [UserUnreadCount] [int] NULL;

IF COL_LENGTH('dbo.Patients', 'ProfilePicturePath') IS NULL ALTER TABLE dbo.[Patients] ADD [ProfilePicturePath] [nvarchar](500) NULL;

IF COL_LENGTH('dbo.Payments', 'CheckDate') IS NULL ALTER TABLE dbo.[Payments] ADD [CheckDate] [date] NULL;
IF COL_LENGTH('dbo.Payments', 'CardReference') IS NULL ALTER TABLE dbo.[Payments] ADD [CardReference] [nvarchar](100) NULL;
IF COL_LENGTH('dbo.Payments', 'ReferenceNumber') IS NULL ALTER TABLE dbo.[Payments] ADD [ReferenceNumber] [nvarchar](100) NULL;

IF COL_LENGTH('dbo.Providers', 'ShowResumePopup') IS NULL ALTER TABLE dbo.[Providers] ADD [ShowResumePopup] [bit] NULL;
IF COL_LENGTH('dbo.Providers', 'ProfilePicturePath') IS NULL ALTER TABLE dbo.[Providers] ADD [ProfilePicturePath] [nvarchar](500) NULL;
GO

-- ----------------------------------------------------------------------------
-- Missing tables
-- ----------------------------------------------------------------------------

IF OBJECT_ID('dbo.PatientPortalAccounts', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PatientPortalAccounts(
        PatientPortalAccountId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
        TenantId INT NOT NULL,
        LocationId INT NOT NULL,
        PatientId INT NOT NULL,
        PasswordHash NVARCHAR(500) NOT NULL,
        IsActive BIT NOT NULL,
        CreatedAt DATETIME2(7) NOT NULL,
        RegisteredAt DATETIME2(7) NULL,
        LastLoginAt DATETIME2(7) NULL,
        FailedLoginAttempts INT NOT NULL,
        LockoutEndAt DATETIME2(7) NULL
    );
    PRINT 'Created PatientPortalAccounts';
END
GO

IF OBJECT_ID('dbo.PatientPortalInvitations', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PatientPortalInvitations(
        PatientPortalInvitationId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
        TenantId INT NOT NULL,
        LocationId INT NOT NULL,
        PatientId INT NOT NULL,
        Email NVARCHAR(256) NOT NULL,
        TokenHash NVARCHAR(500) NOT NULL,
        Status INT NOT NULL,
        InvitedByUserId INT NOT NULL,
        CreatedAt DATETIME2(7) NOT NULL,
        ExpiresAt DATETIME2(7) NOT NULL,
        UsedAt DATETIME2(7) NULL,
        ResentCount INT NOT NULL
    );
    PRINT 'Created PatientPortalInvitations';
END
GO

IF OBJECT_ID('dbo.PatientPortalOtps', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PatientPortalOtps(
        PatientPortalOtpId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
        AccountId INT NOT NULL,
        CodeHash NVARCHAR(500) NOT NULL,
        ExpiresAt DATETIME2(7) NOT NULL,
        AttemptCount INT NOT NULL,
        UsedAt DATETIME2(7) NULL,
        CreatedAt DATETIME2(7) NOT NULL
    );
    PRINT 'Created PatientPortalOtps';
END
GO

IF OBJECT_ID('dbo.PatientPortalPasswordResets', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PatientPortalPasswordResets(
        PatientPortalPasswordResetId INT IDENTITY(1,1) NOT NULL PRIMARY KEY CLUSTERED,
        AccountId INT NOT NULL,
        TokenHash NVARCHAR(500) NOT NULL,
        ExpiresAt DATETIME2(7) NOT NULL,
        UsedAt DATETIME2(7) NULL,
        CreatedAt DATETIME2(7) NOT NULL
    );
    PRINT 'Created PatientPortalPasswordResets';
END
GO

IF OBJECT_ID('dbo.PatientStickyNotes', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.PatientStickyNotes(
        PatientStickyNoteId INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_PatientStickyNotes PRIMARY KEY CLUSTERED,
        TenantId INT NOT NULL,
        PatientId INT NOT NULL,
        Content NVARCHAR(1000) NOT NULL,
        CreatedByUserId INT NOT NULL,
        CreatedByName NVARCHAR(200) NOT NULL,
        CreatedAt DATETIME2(7) NOT NULL,
        UpdatedAt DATETIME2(7) NULL,
        IsDeleted BIT NOT NULL
    );
    PRINT 'Created PatientStickyNotes';
END
GO

PRINT 'Migration 026 complete: schema synced with production (56 columns + 5 tables)';
GO
