-- ============================================================
-- Migration 021: Encounter Summary
-- ============================================================
-- Adds a single column to Encounters for storing the AI-generated
-- patient-friendly visit summary.
--
-- NULL  = no summary generated yet
-- value = current summary (regenerated on close, amendment, addendum)
--
-- Generated by EncounterSummaryManager (server-side, fire-and-forget).
-- Source: signed clinical notes (latest version per note) + addendums
-- with PHI scrubbed via ClinicalNotePHIScrubber before any Gemini call.
-- ============================================================

SET QUOTED_IDENTIFIER ON;
GO

IF NOT EXISTS (
    SELECT 1
    FROM sys.columns
    WHERE object_id = OBJECT_ID('dbo.Encounters')
      AND name = 'SummaryText'
)
BEGIN
    ALTER TABLE dbo.Encounters
    ADD SummaryText nvarchar(max) NULL;
END
GO
