-- ============================================================================
-- Seed ICD-10-CM Codes for Internal Medicine / Primary Care
-- Run once on each environment (local + live).
-- Re-runnable safely — guarded by IF NOT EXISTS on a sentinel code.
--
-- Coverage strategy: include enough codes per common IM category so the
-- "Family Dropdown" UX (3-character prefix expansion) is actually useful.
-- ============================================================================

IF NOT EXISTS (SELECT 1 FROM Icdcodes WHERE Code = 'E11.65')
BEGIN

INSERT INTO Icdcodes (Code, Description, Category, IsActive) VALUES

-- ============================================================================
-- ENDOCRINE / METABOLIC
-- ============================================================================
-- Type 2 Diabetes Mellitus (E11.x family — full expansion)
('E11.00',  'Type 2 diabetes mellitus with hyperosmolarity without nonketotic hyperglycemic-hyperosmolar coma', 'Endocrine', 1),
('E11.01',  'Type 2 diabetes mellitus with hyperosmolarity with coma', 'Endocrine', 1),
('E11.10',  'Type 2 diabetes mellitus with ketoacidosis without coma', 'Endocrine', 1),
('E11.11',  'Type 2 diabetes mellitus with ketoacidosis with coma', 'Endocrine', 1),
('E11.21',  'Type 2 diabetes mellitus with diabetic nephropathy', 'Endocrine', 1),
('E11.22',  'Type 2 diabetes mellitus with diabetic chronic kidney disease', 'Endocrine', 1),
('E11.29',  'Type 2 diabetes mellitus with other diabetic kidney complication', 'Endocrine', 1),
('E11.311', 'Type 2 diabetes mellitus with unspecified diabetic retinopathy with macular edema', 'Endocrine', 1),
('E11.319', 'Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema', 'Endocrine', 1),
('E11.36',  'Type 2 diabetes mellitus with diabetic cataract', 'Endocrine', 1),
('E11.40',  'Type 2 diabetes mellitus with diabetic neuropathy, unspecified', 'Endocrine', 1),
('E11.41',  'Type 2 diabetes mellitus with diabetic mononeuropathy', 'Endocrine', 1),
('E11.42',  'Type 2 diabetes mellitus with diabetic polyneuropathy', 'Endocrine', 1),
('E11.43',  'Type 2 diabetes mellitus with diabetic autonomic (poly)neuropathy', 'Endocrine', 1),
('E11.44',  'Type 2 diabetes mellitus with diabetic amyotrophy', 'Endocrine', 1),
('E11.49',  'Type 2 diabetes mellitus with other diabetic neurological complication', 'Endocrine', 1),
('E11.51',  'Type 2 diabetes mellitus with diabetic peripheral angiopathy without gangrene', 'Endocrine', 1),
('E11.52',  'Type 2 diabetes mellitus with diabetic peripheral angiopathy with gangrene', 'Endocrine', 1),
('E11.59',  'Type 2 diabetes mellitus with other circulatory complications', 'Endocrine', 1),
('E11.610', 'Type 2 diabetes mellitus with diabetic neuropathic arthropathy', 'Endocrine', 1),
('E11.621', 'Type 2 diabetes mellitus with foot ulcer', 'Endocrine', 1),
('E11.622', 'Type 2 diabetes mellitus with other skin ulcer', 'Endocrine', 1),
('E11.628', 'Type 2 diabetes mellitus with other skin complications', 'Endocrine', 1),
('E11.630', 'Type 2 diabetes mellitus with periodontal disease', 'Endocrine', 1),
('E11.638', 'Type 2 diabetes mellitus with other oral complications', 'Endocrine', 1),
('E11.641', 'Type 2 diabetes mellitus with hypoglycemia with coma', 'Endocrine', 1),
('E11.649', 'Type 2 diabetes mellitus with hypoglycemia without coma', 'Endocrine', 1),
('E11.65',  'Type 2 diabetes mellitus with hyperglycemia', 'Endocrine', 1),
('E11.69',  'Type 2 diabetes mellitus with other specified complication', 'Endocrine', 1),
('E11.8',   'Type 2 diabetes mellitus with unspecified complications', 'Endocrine', 1),
('E11.9',   'Type 2 diabetes mellitus without complications', 'Endocrine', 1),

-- Type 1 Diabetes Mellitus (E10.x family)
('E10.10',  'Type 1 diabetes mellitus with ketoacidosis without coma', 'Endocrine', 1),
('E10.11',  'Type 1 diabetes mellitus with ketoacidosis with coma', 'Endocrine', 1),
('E10.21',  'Type 1 diabetes mellitus with diabetic nephropathy', 'Endocrine', 1),
('E10.22',  'Type 1 diabetes mellitus with diabetic chronic kidney disease', 'Endocrine', 1),
('E10.29',  'Type 1 diabetes mellitus with other diabetic kidney complication', 'Endocrine', 1),
('E10.40',  'Type 1 diabetes mellitus with diabetic neuropathy, unspecified', 'Endocrine', 1),
('E10.42',  'Type 1 diabetes mellitus with diabetic polyneuropathy', 'Endocrine', 1),
('E10.51',  'Type 1 diabetes mellitus with diabetic peripheral angiopathy without gangrene', 'Endocrine', 1),
('E10.621', 'Type 1 diabetes mellitus with foot ulcer', 'Endocrine', 1),
('E10.65',  'Type 1 diabetes mellitus with hyperglycemia', 'Endocrine', 1),
('E10.649', 'Type 1 diabetes mellitus with hypoglycemia without coma', 'Endocrine', 1),
('E10.8',   'Type 1 diabetes mellitus with unspecified complications', 'Endocrine', 1),
('E10.9',   'Type 1 diabetes mellitus without complications', 'Endocrine', 1),

-- Pre-diabetes / abnormal glucose
('E13.9',   'Other specified diabetes mellitus without complications', 'Endocrine', 1),
('R73.01',  'Impaired fasting glucose', 'Endocrine', 1),
('R73.02',  'Impaired glucose tolerance (oral)', 'Endocrine', 1),
('R73.03',  'Prediabetes', 'Endocrine', 1),
('R73.09',  'Other abnormal glucose', 'Endocrine', 1),
('R73.9',   'Hyperglycemia, unspecified', 'Endocrine', 1),
('E16.2',   'Hypoglycemia, unspecified', 'Endocrine', 1),

-- Lipid disorders (E78.x family)
('E78.00',  'Pure hypercholesterolemia, unspecified', 'Endocrine', 1),
('E78.01',  'Familial hypercholesterolemia', 'Endocrine', 1),
('E78.1',   'Pure hyperglyceridemia', 'Endocrine', 1),
('E78.2',   'Mixed hyperlipidemia', 'Endocrine', 1),
('E78.3',   'Hyperchylomicronemia', 'Endocrine', 1),
('E78.4',   'Other hyperlipidemia', 'Endocrine', 1),
('E78.41',  'Elevated lipoprotein(a)', 'Endocrine', 1),
('E78.49',  'Other hyperlipidemia', 'Endocrine', 1),
('E78.5',   'Hyperlipidemia, unspecified', 'Endocrine', 1),
('E78.6',   'Lipoprotein deficiency', 'Endocrine', 1),
('E78.70',  'Disorder of bile acid and cholesterol metabolism, unspecified', 'Endocrine', 1),
('E78.79',  'Other disorders of bile acid and cholesterol metabolism', 'Endocrine', 1),
('E78.81',  'Lipoid dermatoarthritis', 'Endocrine', 1),
('E78.89',  'Other lipoprotein metabolism disorders', 'Endocrine', 1),
('E78.9',   'Disorder of lipoprotein metabolism, unspecified', 'Endocrine', 1),

-- Thyroid disorders
('E03.0',   'Congenital hypothyroidism with diffuse goiter', 'Endocrine', 1),
('E03.1',   'Congenital hypothyroidism without goiter', 'Endocrine', 1),
('E03.2',   'Hypothyroidism due to medicaments and other exogenous substances', 'Endocrine', 1),
('E03.3',   'Postinfectious hypothyroidism', 'Endocrine', 1),
('E03.4',   'Atrophy of thyroid (acquired)', 'Endocrine', 1),
('E03.5',   'Myxedema coma', 'Endocrine', 1),
('E03.8',   'Other specified hypothyroidism', 'Endocrine', 1),
('E03.9',   'Hypothyroidism, unspecified', 'Endocrine', 1),
('E04.0',   'Nontoxic diffuse goiter', 'Endocrine', 1),
('E04.1',   'Nontoxic single thyroid nodule', 'Endocrine', 1),
('E04.2',   'Nontoxic multinodular goiter', 'Endocrine', 1),
('E04.9',   'Nontoxic goiter, unspecified', 'Endocrine', 1),
('E05.00',  'Thyrotoxicosis with diffuse goiter without thyrotoxic crisis', 'Endocrine', 1),
('E05.10',  'Thyrotoxicosis with toxic single thyroid nodule without thyrotoxic crisis', 'Endocrine', 1),
('E05.20',  'Thyrotoxicosis with toxic multinodular goiter without thyrotoxic crisis', 'Endocrine', 1),
('E05.90',  'Thyrotoxicosis, unspecified, without thyrotoxic crisis or storm', 'Endocrine', 1),
('E06.3',   'Autoimmune thyroiditis', 'Endocrine', 1),
('E06.9',   'Thyroiditis, unspecified', 'Endocrine', 1),
('E07.9',   'Disorder of thyroid, unspecified', 'Endocrine', 1),

-- Obesity (E66.x family)
('E66.01',  'Morbid (severe) obesity due to excess calories', 'Endocrine', 1),
('E66.09',  'Other obesity due to excess calories', 'Endocrine', 1),
('E66.1',   'Drug-induced obesity', 'Endocrine', 1),
('E66.2',   'Morbid (severe) obesity with alveolar hypoventilation', 'Endocrine', 1),
('E66.3',   'Overweight', 'Endocrine', 1),
('E66.8',   'Other obesity', 'Endocrine', 1),
('E66.9',   'Obesity, unspecified', 'Endocrine', 1),

-- Vitamin/electrolyte
('E55.9',   'Vitamin D deficiency, unspecified', 'Endocrine', 1),
('E53.8',   'Deficiency of other specified B group vitamins', 'Endocrine', 1),
('E61.1',   'Iron deficiency', 'Endocrine', 1),
('E83.42',  'Hypomagnesemia', 'Endocrine', 1),
('E87.1',   'Hypo-osmolality and hyponatremia', 'Endocrine', 1),
('E87.5',   'Hyperkalemia', 'Endocrine', 1),
('E87.6',   'Hypokalemia', 'Endocrine', 1),
('E86.0',   'Dehydration', 'Endocrine', 1),
('E89.0',   'Postprocedural hypothyroidism', 'Endocrine', 1),

-- ============================================================================
-- CIRCULATORY
-- ============================================================================
-- Hypertension
('I10',     'Essential (primary) hypertension', 'Circulatory', 1),
('I11.0',   'Hypertensive heart disease with heart failure', 'Circulatory', 1),
('I11.9',   'Hypertensive heart disease without heart failure', 'Circulatory', 1),
('I12.0',   'Hypertensive chronic kidney disease with stage 5 CKD or ESRD', 'Circulatory', 1),
('I12.9',   'Hypertensive chronic kidney disease with stage 1-4 CKD or unspecified', 'Circulatory', 1),
('I13.0',   'Hypertensive heart and CKD with heart failure, stage 1-4 CKD', 'Circulatory', 1),
('I13.10',  'Hypertensive heart and CKD without heart failure, stage 1-4 CKD', 'Circulatory', 1),
('I13.11',  'Hypertensive heart and CKD without heart failure, stage 5 CKD or ESRD', 'Circulatory', 1),
('I13.2',   'Hypertensive heart and CKD with heart failure, stage 5 CKD or ESRD', 'Circulatory', 1),
('I15.0',   'Renovascular hypertension', 'Circulatory', 1),
('I15.1',   'Hypertension secondary to other renal disorders', 'Circulatory', 1),
('I15.2',   'Hypertension secondary to endocrine disorders', 'Circulatory', 1),
('I15.8',   'Other secondary hypertension', 'Circulatory', 1),
('I15.9',   'Secondary hypertension, unspecified', 'Circulatory', 1),
('I16.0',   'Hypertensive urgency', 'Circulatory', 1),
('I16.1',   'Hypertensive emergency', 'Circulatory', 1),
('I16.9',   'Hypertensive crisis, unspecified', 'Circulatory', 1),

-- Ischemic heart disease (I20-I25)
('I20.0',   'Unstable angina', 'Circulatory', 1),
('I20.1',   'Angina pectoris with documented spasm', 'Circulatory', 1),
('I20.8',   'Other forms of angina pectoris', 'Circulatory', 1),
('I20.9',   'Angina pectoris, unspecified', 'Circulatory', 1),
('I21.3',   'ST elevation (STEMI) myocardial infarction of unspecified site', 'Circulatory', 1),
('I21.4',   'Non-ST elevation (NSTEMI) myocardial infarction', 'Circulatory', 1),
('I21.9',   'Acute myocardial infarction, unspecified', 'Circulatory', 1),
('I25.10',  'Atherosclerotic heart disease of native coronary artery without angina', 'Circulatory', 1),
('I25.110', 'Atherosclerotic heart disease of native coronary artery with unstable angina', 'Circulatory', 1),
('I25.118', 'Atherosclerotic heart disease of native coronary artery with other angina', 'Circulatory', 1),
('I25.119', 'Atherosclerotic heart disease of native coronary artery with unspecified angina', 'Circulatory', 1),
('I25.2',   'Old myocardial infarction', 'Circulatory', 1),
('I25.5',   'Ischemic cardiomyopathy', 'Circulatory', 1),
('I25.9',   'Chronic ischemic heart disease, unspecified', 'Circulatory', 1),

-- Atrial fibrillation / dysrhythmias (I48.x, I49.x)
('I48.0',   'Paroxysmal atrial fibrillation', 'Circulatory', 1),
('I48.11',  'Longstanding persistent atrial fibrillation', 'Circulatory', 1),
('I48.19',  'Other persistent atrial fibrillation', 'Circulatory', 1),
('I48.20',  'Chronic atrial fibrillation, unspecified', 'Circulatory', 1),
('I48.21',  'Permanent atrial fibrillation', 'Circulatory', 1),
('I48.91',  'Unspecified atrial fibrillation', 'Circulatory', 1),
('I48.92',  'Unspecified atrial flutter', 'Circulatory', 1),
('I49.01',  'Ventricular fibrillation', 'Circulatory', 1),
('I49.5',   'Sick sinus syndrome', 'Circulatory', 1),
('I49.8',   'Other specified cardiac arrhythmias', 'Circulatory', 1),
('I49.9',   'Cardiac arrhythmia, unspecified', 'Circulatory', 1),

-- Heart failure (I50.x)
('I50.1',   'Left ventricular failure, unspecified', 'Circulatory', 1),
('I50.20',  'Unspecified systolic (congestive) heart failure', 'Circulatory', 1),
('I50.21',  'Acute systolic (congestive) heart failure', 'Circulatory', 1),
('I50.22',  'Chronic systolic (congestive) heart failure', 'Circulatory', 1),
('I50.23',  'Acute on chronic systolic (congestive) heart failure', 'Circulatory', 1),
('I50.30',  'Unspecified diastolic (congestive) heart failure', 'Circulatory', 1),
('I50.31',  'Acute diastolic (congestive) heart failure', 'Circulatory', 1),
('I50.32',  'Chronic diastolic (congestive) heart failure', 'Circulatory', 1),
('I50.33',  'Acute on chronic diastolic (congestive) heart failure', 'Circulatory', 1),
('I50.40',  'Unspecified combined systolic and diastolic heart failure', 'Circulatory', 1),
('I50.41',  'Acute combined systolic and diastolic heart failure', 'Circulatory', 1),
('I50.42',  'Chronic combined systolic and diastolic heart failure', 'Circulatory', 1),
('I50.43',  'Acute on chronic combined systolic and diastolic heart failure', 'Circulatory', 1),
('I50.9',   'Heart failure, unspecified', 'Circulatory', 1),

-- Cerebrovascular (I60-I69)
('I63.9',   'Cerebral infarction, unspecified', 'Circulatory', 1),
('I65.23',  'Occlusion and stenosis of bilateral carotid arteries', 'Circulatory', 1),
('I65.29',  'Occlusion and stenosis of unspecified carotid artery', 'Circulatory', 1),
('I67.2',   'Cerebral atherosclerosis', 'Circulatory', 1),
('I69.351', 'Hemiplegia/hemiparesis following cerebral infarction affecting right dominant side', 'Circulatory', 1),
('I69.398', 'Other sequelae of cerebral infarction', 'Circulatory', 1),
('G45.9',   'Transient cerebral ischemic attack (TIA), unspecified', 'Circulatory', 1),

-- Peripheral vascular
('I73.9',   'Peripheral vascular disease, unspecified', 'Circulatory', 1),
('I83.90',  'Asymptomatic varicose veins of unspecified lower extremity', 'Circulatory', 1),
('I87.2',   'Venous insufficiency (chronic) (peripheral)', 'Circulatory', 1),

-- Venous thromboembolism
('I80.299', 'Phlebitis and thrombophlebitis of unspecified deep vessels of unspecified lower extremity', 'Circulatory', 1),
('I82.401', 'Acute embolism and thrombosis of unspecified deep veins of right lower extremity', 'Circulatory', 1),
('I82.409', 'Acute embolism and thrombosis of unspecified deep veins of unspecified lower extremity', 'Circulatory', 1),
('I26.99',  'Other pulmonary embolism without acute cor pulmonale', 'Circulatory', 1),

-- ============================================================================
-- RESPIRATORY
-- ============================================================================
('J00',     'Acute nasopharyngitis (common cold)', 'Respiratory', 1),
('J01.90',  'Acute sinusitis, unspecified', 'Respiratory', 1),
('J02.9',   'Acute pharyngitis, unspecified', 'Respiratory', 1),
('J03.90',  'Acute tonsillitis, unspecified', 'Respiratory', 1),
('J04.0',   'Acute laryngitis', 'Respiratory', 1),
('J06.9',   'Acute upper respiratory infection, unspecified', 'Respiratory', 1),
('J11.1',   'Influenza due to unidentified influenza virus with other respiratory manifestations', 'Respiratory', 1),
('J18.0',   'Bronchopneumonia, unspecified organism', 'Respiratory', 1),
('J18.1',   'Lobar pneumonia, unspecified organism', 'Respiratory', 1),
('J18.9',   'Pneumonia, unspecified organism', 'Respiratory', 1),
('J20.9',   'Acute bronchitis, unspecified', 'Respiratory', 1),

-- Chronic respiratory (COPD, asthma)
('J32.0',   'Chronic maxillary sinusitis', 'Respiratory', 1),
('J32.9',   'Chronic sinusitis, unspecified', 'Respiratory', 1),
('J40',     'Bronchitis, not specified as acute or chronic', 'Respiratory', 1),
('J41.0',   'Simple chronic bronchitis', 'Respiratory', 1),
('J42',     'Unspecified chronic bronchitis', 'Respiratory', 1),
('J43.9',   'Emphysema, unspecified', 'Respiratory', 1),
('J44.0',   'COPD with acute lower respiratory infection', 'Respiratory', 1),
('J44.1',   'COPD with (acute) exacerbation', 'Respiratory', 1),
('J44.9',   'Chronic obstructive pulmonary disease, unspecified', 'Respiratory', 1),
('J45.20',  'Mild intermittent asthma, uncomplicated', 'Respiratory', 1),
('J45.21',  'Mild intermittent asthma with (acute) exacerbation', 'Respiratory', 1),
('J45.22',  'Mild intermittent asthma with status asthmaticus', 'Respiratory', 1),
('J45.30',  'Mild persistent asthma, uncomplicated', 'Respiratory', 1),
('J45.31',  'Mild persistent asthma with (acute) exacerbation', 'Respiratory', 1),
('J45.40',  'Moderate persistent asthma, uncomplicated', 'Respiratory', 1),
('J45.41',  'Moderate persistent asthma with (acute) exacerbation', 'Respiratory', 1),
('J45.50',  'Severe persistent asthma, uncomplicated', 'Respiratory', 1),
('J45.51',  'Severe persistent asthma with (acute) exacerbation', 'Respiratory', 1),
('J45.901', 'Unspecified asthma with (acute) exacerbation', 'Respiratory', 1),
('J45.909', 'Unspecified asthma, uncomplicated', 'Respiratory', 1),
('J45.998', 'Other asthma', 'Respiratory', 1),

-- Sleep / hypoxia / OSA
('G47.30',  'Sleep apnea, unspecified', 'Respiratory', 1),
('G47.33',  'Obstructive sleep apnea (adult) (pediatric)', 'Respiratory', 1),
('J96.00',  'Acute respiratory failure, unspecified whether with hypoxia or hypercapnia', 'Respiratory', 1),
('J96.01',  'Acute respiratory failure with hypoxia', 'Respiratory', 1),
('J96.21',  'Acute and chronic respiratory failure with hypoxia', 'Respiratory', 1),
('J98.4',   'Other disorders of lung', 'Respiratory', 1),
('R09.02',  'Hypoxemia', 'Respiratory', 1),

-- ============================================================================
-- DIGESTIVE
-- ============================================================================
('K21.0',   'Gastro-esophageal reflux disease with esophagitis', 'Digestive', 1),
('K21.00',  'GERD with esophagitis, without bleeding', 'Digestive', 1),
('K21.9',   'Gastro-esophageal reflux disease without esophagitis', 'Digestive', 1),
('K25.9',   'Gastric ulcer, unspecified, without bleeding/perforation', 'Digestive', 1),
('K29.70',  'Gastritis, unspecified, without bleeding', 'Digestive', 1),
('K30',     'Functional dyspepsia', 'Digestive', 1),
('K52.9',   'Noninfective gastroenteritis and colitis, unspecified', 'Digestive', 1),
('K57.30',  'Diverticulosis of large intestine without perforation/abscess without bleeding', 'Digestive', 1),
('K57.32',  'Diverticulitis of large intestine without perforation/abscess without bleeding', 'Digestive', 1),
('K58.0',   'Irritable bowel syndrome with diarrhea', 'Digestive', 1),
('K58.1',   'Irritable bowel syndrome with constipation', 'Digestive', 1),
('K58.2',   'Mixed irritable bowel syndrome', 'Digestive', 1),
('K58.9',   'Irritable bowel syndrome without diarrhea', 'Digestive', 1),
('K59.00',  'Constipation, unspecified', 'Digestive', 1),
('K59.01',  'Slow transit constipation', 'Digestive', 1),
('K59.09',  'Other constipation', 'Digestive', 1),
('K59.1',   'Functional diarrhea', 'Digestive', 1),
('K63.5',   'Polyp of colon', 'Digestive', 1),
('K70.30',  'Alcoholic cirrhosis of liver without ascites', 'Digestive', 1),
('K74.60',  'Unspecified cirrhosis of liver', 'Digestive', 1),
('K76.0',   'Fatty (change of) liver, not elsewhere classified', 'Digestive', 1),
('K80.20',  'Calculus of gallbladder without cholecystitis without obstruction', 'Digestive', 1),
('K81.9',   'Cholecystitis, unspecified', 'Digestive', 1),
('K92.1',   'Melena', 'Digestive', 1),
('K92.2',   'Gastrointestinal hemorrhage, unspecified', 'Digestive', 1),

-- ============================================================================
-- GENITOURINARY
-- ============================================================================
-- Chronic kidney disease (N18.x)
('N18.1',   'Chronic kidney disease, stage 1', 'Genitourinary', 1),
('N18.2',   'Chronic kidney disease, stage 2 (mild)', 'Genitourinary', 1),
('N18.30',  'Chronic kidney disease, stage 3 unspecified', 'Genitourinary', 1),
('N18.31',  'Chronic kidney disease, stage 3a', 'Genitourinary', 1),
('N18.32',  'Chronic kidney disease, stage 3b', 'Genitourinary', 1),
('N18.4',   'Chronic kidney disease, stage 4 (severe)', 'Genitourinary', 1),
('N18.5',   'Chronic kidney disease, stage 5', 'Genitourinary', 1),
('N18.6',   'End stage renal disease', 'Genitourinary', 1),
('N18.9',   'Chronic kidney disease, unspecified', 'Genitourinary', 1),

-- UTI / cystitis (N30, N39)
('N30.00',  'Acute cystitis without hematuria', 'Genitourinary', 1),
('N30.01',  'Acute cystitis with hematuria', 'Genitourinary', 1),
('N30.10',  'Interstitial cystitis (chronic) without hematuria', 'Genitourinary', 1),
('N30.90',  'Cystitis, unspecified without hematuria', 'Genitourinary', 1),
('N39.0',   'Urinary tract infection, site not specified', 'Genitourinary', 1),
('N39.3',   'Stress incontinence (female) (male)', 'Genitourinary', 1),
('N39.41',  'Urge incontinence', 'Genitourinary', 1),
('N39.46',  'Mixed incontinence', 'Genitourinary', 1),
('N39.498', 'Other specified urinary incontinence', 'Genitourinary', 1),

-- BPH / prostate
('N40.0',   'Benign prostatic hyperplasia without lower urinary tract symptoms', 'Genitourinary', 1),
('N40.1',   'Benign prostatic hyperplasia with lower urinary tract symptoms', 'Genitourinary', 1),
('N40.3',   'Nodular prostate without lower urinary tract symptoms', 'Genitourinary', 1),

-- Other
('N20.0',   'Calculus of kidney', 'Genitourinary', 1),
('N20.1',   'Calculus of ureter', 'Genitourinary', 1),
('N20.9',   'Urinary calculus, unspecified', 'Genitourinary', 1),
('N91.2',   'Amenorrhea, unspecified', 'Genitourinary', 1),
('N92.0',   'Excessive and frequent menstruation with regular cycle', 'Genitourinary', 1),
('N94.6',   'Dysmenorrhea, unspecified', 'Genitourinary', 1),
('N95.1',   'Menopausal and female climacteric states', 'Genitourinary', 1),
('R31.9',   'Hematuria, unspecified', 'Genitourinary', 1),
('R32',     'Unspecified urinary incontinence', 'Genitourinary', 1),
('R33.9',   'Retention of urine, unspecified', 'Genitourinary', 1),
('R35.0',   'Frequency of micturition', 'Genitourinary', 1),

-- ============================================================================
-- MENTAL / BEHAVIORAL
-- ============================================================================
-- Depression (F32.x, F33.x)
('F32.0',   'Major depressive disorder, single episode, mild', 'Mental', 1),
('F32.1',   'Major depressive disorder, single episode, moderate', 'Mental', 1),
('F32.2',   'Major depressive disorder, single episode, severe without psychotic features', 'Mental', 1),
('F32.3',   'Major depressive disorder, single episode, severe with psychotic features', 'Mental', 1),
('F32.4',   'Major depressive disorder, single episode, in partial remission', 'Mental', 1),
('F32.5',   'Major depressive disorder, single episode, in full remission', 'Mental', 1),
('F32.9',   'Major depressive disorder, single episode, unspecified', 'Mental', 1),
('F32.A',   'Depression, unspecified', 'Mental', 1),
('F33.0',   'Major depressive disorder, recurrent, mild', 'Mental', 1),
('F33.1',   'Major depressive disorder, recurrent, moderate', 'Mental', 1),
('F33.2',   'Major depressive disorder, recurrent severe without psychotic features', 'Mental', 1),
('F33.3',   'Major depressive disorder, recurrent, severe with psychotic symptoms', 'Mental', 1),
('F33.40',  'Major depressive disorder, recurrent, in remission, unspecified', 'Mental', 1),
('F33.9',   'Major depressive disorder, recurrent, unspecified', 'Mental', 1),

-- Anxiety (F41.x)
('F41.0',   'Panic disorder without agoraphobia', 'Mental', 1),
('F41.1',   'Generalized anxiety disorder', 'Mental', 1),
('F41.3',   'Other mixed anxiety disorders', 'Mental', 1),
('F41.8',   'Other specified anxiety disorders', 'Mental', 1),
('F41.9',   'Anxiety disorder, unspecified', 'Mental', 1),
('F40.10',  'Social phobia, unspecified', 'Mental', 1),
('F43.0',   'Acute stress reaction', 'Mental', 1),
('F43.10',  'Post-traumatic stress disorder, unspecified', 'Mental', 1),
('F43.20',  'Adjustment disorder, unspecified', 'Mental', 1),
('F43.21',  'Adjustment disorder with depressed mood', 'Mental', 1),
('F43.22',  'Adjustment disorder with anxiety', 'Mental', 1),
('F43.23',  'Adjustment disorder with mixed anxiety and depressed mood', 'Mental', 1),

-- Bipolar / other
('F31.9',   'Bipolar disorder, unspecified', 'Mental', 1),
('F39',     'Unspecified mood [affective] disorder', 'Mental', 1),

-- Substance use
('F10.10',  'Alcohol abuse, uncomplicated', 'Mental', 1),
('F10.20',  'Alcohol dependence, uncomplicated', 'Mental', 1),
('F10.99',  'Alcohol use, unspecified with unspecified alcohol-induced disorder', 'Mental', 1),
('F11.20',  'Opioid dependence, uncomplicated', 'Mental', 1),
('F17.200', 'Nicotine dependence, unspecified, uncomplicated', 'Mental', 1),
('F17.210', 'Nicotine dependence, cigarettes, uncomplicated', 'Mental', 1),
('F17.211', 'Nicotine dependence, cigarettes, in remission', 'Mental', 1),
('F17.220', 'Nicotine dependence, chewing tobacco, uncomplicated', 'Mental', 1),
('F17.290', 'Nicotine dependence, other tobacco product, uncomplicated', 'Mental', 1),

-- Cognitive
('F03.90',  'Unspecified dementia without behavioral disturbance', 'Mental', 1),
('F03.91',  'Unspecified dementia with behavioral disturbance', 'Mental', 1),
('F05',     'Delirium due to known physiological condition', 'Mental', 1),
('G31.84',  'Mild cognitive impairment, so stated', 'Mental', 1),
('G30.9',   'Alzheimer''s disease, unspecified', 'Mental', 1),

-- Insomnia / sleep
('G47.00',  'Insomnia, unspecified', 'Mental', 1),
('G47.01',  'Insomnia due to medical condition', 'Mental', 1),
('G47.09',  'Other insomnia', 'Mental', 1),
('F51.01',  'Primary insomnia', 'Mental', 1),

-- ADHD / behavioral
('F90.0',   'Attention-deficit hyperactivity disorder, predominantly inattentive type', 'Mental', 1),
('F90.1',   'Attention-deficit hyperactivity disorder, predominantly hyperactive type', 'Mental', 1),
('F90.2',   'Attention-deficit hyperactivity disorder, combined type', 'Mental', 1),
('F90.9',   'Attention-deficit hyperactivity disorder, unspecified type', 'Mental', 1),

-- ============================================================================
-- MUSCULOSKELETAL
-- ============================================================================
-- Osteoarthritis (M15-M19)
('M15.0',   'Primary generalized (osteo)arthritis', 'Musculoskeletal', 1),
('M17.0',   'Bilateral primary osteoarthritis of knee', 'Musculoskeletal', 1),
('M17.10',  'Unilateral primary osteoarthritis, unspecified knee', 'Musculoskeletal', 1),
('M17.11',  'Unilateral primary osteoarthritis, right knee', 'Musculoskeletal', 1),
('M17.12',  'Unilateral primary osteoarthritis, left knee', 'Musculoskeletal', 1),
('M19.011', 'Primary osteoarthritis, right shoulder', 'Musculoskeletal', 1),
('M19.012', 'Primary osteoarthritis, left shoulder', 'Musculoskeletal', 1),
('M19.90',  'Unspecified osteoarthritis, unspecified site', 'Musculoskeletal', 1),
('M19.91',  'Primary osteoarthritis, unspecified site', 'Musculoskeletal', 1),

-- Joint pain (M25.5x)
('M25.50',  'Pain in unspecified joint', 'Musculoskeletal', 1),
('M25.511', 'Pain in right shoulder', 'Musculoskeletal', 1),
('M25.512', 'Pain in left shoulder', 'Musculoskeletal', 1),
('M25.561', 'Pain in right knee', 'Musculoskeletal', 1),
('M25.562', 'Pain in left knee', 'Musculoskeletal', 1),
('M25.571', 'Pain in right ankle and joints of right foot', 'Musculoskeletal', 1),
('M25.572', 'Pain in left ankle and joints of left foot', 'Musculoskeletal', 1),

-- Back pain (M54.x family)
('M54.10',  'Radiculopathy, site unspecified', 'Musculoskeletal', 1),
('M54.12',  'Radiculopathy, cervical region', 'Musculoskeletal', 1),
('M54.16',  'Radiculopathy, lumbar region', 'Musculoskeletal', 1),
('M54.17',  'Radiculopathy, lumbosacral region', 'Musculoskeletal', 1),
('M54.2',   'Cervicalgia', 'Musculoskeletal', 1),
('M54.30',  'Sciatica, unspecified side', 'Musculoskeletal', 1),
('M54.31',  'Sciatica, right side', 'Musculoskeletal', 1),
('M54.32',  'Sciatica, left side', 'Musculoskeletal', 1),
('M54.40',  'Lumbago with sciatica, unspecified side', 'Musculoskeletal', 1),
('M54.5',   'Low back pain', 'Musculoskeletal', 1),
('M54.50',  'Low back pain, unspecified', 'Musculoskeletal', 1),
('M54.51',  'Vertebrogenic low back pain', 'Musculoskeletal', 1),
('M54.59',  'Other low back pain', 'Musculoskeletal', 1),
('M54.6',   'Pain in thoracic spine', 'Musculoskeletal', 1),
('M54.81',  'Occipital neuralgia', 'Musculoskeletal', 1),
('M54.89',  'Other dorsalgia', 'Musculoskeletal', 1),
('M54.9',   'Dorsalgia, unspecified', 'Musculoskeletal', 1),

-- Soft tissue / fibromyalgia
('M79.1',   'Myalgia', 'Musculoskeletal', 1),
('M79.10',  'Myalgia, unspecified site', 'Musculoskeletal', 1),
('M79.18',  'Myalgia, other site', 'Musculoskeletal', 1),
('M79.7',   'Fibromyalgia', 'Musculoskeletal', 1),

-- Osteoporosis
('M81.0',   'Age-related osteoporosis without current pathological fracture', 'Musculoskeletal', 1),
('M81.6',   'Localized osteoporosis [Lequesne]', 'Musculoskeletal', 1),
('M81.8',   'Other osteoporosis without current pathological fracture', 'Musculoskeletal', 1),
('M85.80',  'Other specified disorders of bone density and structure, unspecified site', 'Musculoskeletal', 1),

-- Gout
('M10.00',  'Idiopathic gout, unspecified site', 'Musculoskeletal', 1),
('M10.071', 'Idiopathic gout, right ankle and foot', 'Musculoskeletal', 1),
('M10.9',   'Gout, unspecified', 'Musculoskeletal', 1),

-- ============================================================================
-- BLOOD / ANEMIAS
-- ============================================================================
('D50.0',   'Iron deficiency anemia secondary to blood loss (chronic)', 'Blood', 1),
('D50.8',   'Other iron deficiency anemias', 'Blood', 1),
('D50.9',   'Iron deficiency anemia, unspecified', 'Blood', 1),
('D51.0',   'Vitamin B12 deficiency anemia due to intrinsic factor deficiency', 'Blood', 1),
('D51.9',   'Vitamin B12 deficiency anemia, unspecified', 'Blood', 1),
('D52.9',   'Folate deficiency anemia, unspecified', 'Blood', 1),
('D53.9',   'Nutritional anemia, unspecified', 'Blood', 1),
('D62',     'Acute posthemorrhagic anemia', 'Blood', 1),
('D63.1',   'Anemia in chronic kidney disease', 'Blood', 1),
('D63.8',   'Anemia in other chronic diseases classified elsewhere', 'Blood', 1),
('D64.1',   'Secondary sideroblastic anemia due to disease', 'Blood', 1),
('D64.81',  'Anemia due to antineoplastic chemotherapy', 'Blood', 1),
('D64.89',  'Other specified anemias', 'Blood', 1),
('D64.9',   'Anemia, unspecified', 'Blood', 1),
('D68.51',  'Activated protein C resistance', 'Blood', 1),
('D68.69',  'Other thrombophilia', 'Blood', 1),
('D69.6',   'Thrombocytopenia, unspecified', 'Blood', 1),
('D72.829', 'Elevated white blood cell count, unspecified', 'Blood', 1),

-- ============================================================================
-- SYMPTOMS / SIGNS (R-codes)
-- ============================================================================
('R00.0',   'Tachycardia, unspecified', 'Symptoms', 1),
('R00.1',   'Bradycardia, unspecified', 'Symptoms', 1),
('R00.2',   'Palpitations', 'Symptoms', 1),
('R03.0',   'Elevated blood-pressure reading, without diagnosis of hypertension', 'Symptoms', 1),
('R05.1',   'Acute cough', 'Symptoms', 1),
('R05.3',   'Chronic cough', 'Symptoms', 1),
('R05.9',   'Cough, unspecified', 'Symptoms', 1),
('R06.00',  'Dyspnea, unspecified', 'Symptoms', 1),
('R06.02',  'Shortness of breath', 'Symptoms', 1),
('R06.2',   'Wheezing', 'Symptoms', 1),
('R06.83',  'Snoring', 'Symptoms', 1),
('R07.0',   'Pain in throat', 'Symptoms', 1),
('R07.1',   'Chest pain on breathing', 'Symptoms', 1),
('R07.2',   'Precordial pain', 'Symptoms', 1),
('R07.81',  'Pleurodynia', 'Symptoms', 1),
('R07.82',  'Intercostal pain', 'Symptoms', 1),
('R07.89',  'Other chest pain', 'Symptoms', 1),
('R07.9',   'Chest pain, unspecified', 'Symptoms', 1),
('R10.0',   'Acute abdomen', 'Symptoms', 1),
('R10.10',  'Upper abdominal pain, unspecified', 'Symptoms', 1),
('R10.11',  'Right upper quadrant pain', 'Symptoms', 1),
('R10.12',  'Left upper quadrant pain', 'Symptoms', 1),
('R10.13',  'Epigastric pain', 'Symptoms', 1),
('R10.30',  'Lower abdominal pain, unspecified', 'Symptoms', 1),
('R10.31',  'Right lower quadrant pain', 'Symptoms', 1),
('R10.32',  'Left lower quadrant pain', 'Symptoms', 1),
('R10.33',  'Periumbilical pain', 'Symptoms', 1),
('R10.84',  'Generalized abdominal pain', 'Symptoms', 1),
('R10.9',   'Unspecified abdominal pain', 'Symptoms', 1),
('R11.0',   'Nausea', 'Symptoms', 1),
('R11.10',  'Vomiting, unspecified', 'Symptoms', 1),
('R11.2',   'Nausea with vomiting, unspecified', 'Symptoms', 1),
('R19.7',   'Diarrhea, unspecified', 'Symptoms', 1),
('R21',     'Rash and other nonspecific skin eruption', 'Symptoms', 1),
('R22.0',   'Localized swelling, mass and lump, head', 'Symptoms', 1),
('R22.41',  'Localized swelling, mass and lump, right lower limb', 'Symptoms', 1),
('R22.42',  'Localized swelling, mass and lump, left lower limb', 'Symptoms', 1),
('R26.81',  'Unsteadiness on feet', 'Symptoms', 1),
('R26.89',  'Other abnormalities of gait and mobility', 'Symptoms', 1),
('R26.9',   'Unspecified abnormalities of gait and mobility', 'Symptoms', 1),
('R29.6',   'Repeated falls', 'Symptoms', 1),
('R31.0',   'Gross hematuria', 'Symptoms', 1),
('R31.1',   'Benign essential microscopic hematuria', 'Symptoms', 1),
('R35.1',   'Nocturia', 'Symptoms', 1),
('R39.81',  'Functional urinary incontinence', 'Symptoms', 1),
('R41.3',   'Other amnesia', 'Symptoms', 1),
('R41.81',  'Age-related cognitive decline', 'Symptoms', 1),
('R41.840', 'Attention and concentration deficit', 'Symptoms', 1),
('R42',     'Dizziness and giddiness', 'Symptoms', 1),
('R45.0',   'Nervousness', 'Symptoms', 1),
('R45.1',   'Restlessness and agitation', 'Symptoms', 1),
('R45.851', 'Suicidal ideations', 'Symptoms', 1),
('R47.81',  'Slurred speech', 'Symptoms', 1),
('R50.9',   'Fever, unspecified', 'Symptoms', 1),
('R51.0',   'Headache with orthostatic component, not elsewhere classified', 'Symptoms', 1),
('R51.9',   'Headache, unspecified', 'Symptoms', 1),
('R53.1',   'Weakness', 'Symptoms', 1),
('R53.81',  'Other malaise', 'Symptoms', 1),
('R53.82',  'Chronic fatigue, unspecified', 'Symptoms', 1),
('R53.83',  'Other fatigue', 'Symptoms', 1),
('R55',     'Syncope and collapse', 'Symptoms', 1),
('R56.9',   'Unspecified convulsions', 'Symptoms', 1),
('R60.0',   'Localized edema', 'Symptoms', 1),
('R60.1',   'Generalized edema', 'Symptoms', 1),
('R60.9',   'Edema, unspecified', 'Symptoms', 1),
('R63.0',   'Anorexia', 'Symptoms', 1),
('R63.4',   'Abnormal weight loss', 'Symptoms', 1),
('R63.5',   'Abnormal weight gain', 'Symptoms', 1),
('R63.6',   'Underweight', 'Symptoms', 1),
('R68.84',  'Jaw pain', 'Symptoms', 1),
('R74.0',   'Nonspecific elevation of levels of transaminase and lactic acid dehydrogenase', 'Symptoms', 1),
('R74.8',   'Abnormal levels of other serum enzymes', 'Symptoms', 1),
('R76.11',  'Nonspecific reaction to test for tuberculosis without active TB', 'Symptoms', 1),
('R79.89',  'Other specified abnormal findings of blood chemistry', 'Symptoms', 1),
('R80.9',   'Proteinuria, unspecified', 'Symptoms', 1),
('R82.71',  'Bacteriuria', 'Symptoms', 1),
('R82.79',  'Other abnormal findings on microbiological exam of urine', 'Symptoms', 1),
('R82.81',  'Pyuria', 'Symptoms', 1),
('R91.8',   'Other nonspecific abnormal finding of lung field', 'Symptoms', 1),
('R94.5',   'Abnormal results of liver function studies', 'Symptoms', 1),
('R94.8',   'Abnormal results of function studies of other organs and systems', 'Symptoms', 1),

-- ============================================================================
-- SKIN
-- ============================================================================
('L20.9',   'Atopic dermatitis, unspecified', 'Skin', 1),
('L23.9',   'Allergic contact dermatitis, unspecified cause', 'Skin', 1),
('L25.9',   'Unspecified contact dermatitis, unspecified cause', 'Skin', 1),
('L29.9',   'Pruritus, unspecified', 'Skin', 1),
('L30.9',   'Dermatitis, unspecified', 'Skin', 1),
('L40.9',   'Psoriasis, unspecified', 'Skin', 1),
('L50.9',   'Urticaria, unspecified', 'Skin', 1),
('L70.0',   'Acne vulgaris', 'Skin', 1),
('L70.9',   'Acne, unspecified', 'Skin', 1),
('L72.3',   'Sebaceous cyst', 'Skin', 1),
('L80',     'Vitiligo', 'Skin', 1),
('L82.1',   'Other seborrheic keratosis', 'Skin', 1),
('L98.9',   'Disorder of the skin and subcutaneous tissue, unspecified', 'Skin', 1),

-- ============================================================================
-- INFECTIOUS / IMMUNE
-- ============================================================================
('A04.7',   'Enterocolitis due to Clostridium difficile', 'Infectious', 1),
('A09',     'Infectious gastroenteritis and colitis, unspecified', 'Infectious', 1),
('A41.9',   'Sepsis, unspecified organism', 'Infectious', 1),
('B02.9',   'Zoster without complications', 'Infectious', 1),
('B19.20',  'Unspecified viral hepatitis C without hepatic coma', 'Infectious', 1),
('B20',     'Human immunodeficiency virus [HIV] disease', 'Infectious', 1),
('B34.9',   'Viral infection, unspecified', 'Infectious', 1),
('B96.20',  'Unspecified Escherichia coli as the cause of diseases classified elsewhere', 'Infectious', 1),
('B96.89',  'Other specified bacterial agents as the cause of diseases classified elsewhere', 'Infectious', 1),
('B97.89',  'Other viral agents as the cause of diseases classified elsewhere', 'Infectious', 1),
('U07.1',   'COVID-19', 'Infectious', 1),
('U09.9',   'Post COVID-19 condition, unspecified', 'Infectious', 1),

-- ============================================================================
-- EYE / EAR / NEUROLOGY (selected, common in IM)
-- ============================================================================
('H10.9',   'Unspecified conjunctivitis', 'Eye', 1),
('H25.13',  'Age-related nuclear cataract, bilateral', 'Eye', 1),
('H40.10',  'Unspecified open-angle glaucoma', 'Eye', 1),
('H53.9',   'Unspecified visual disturbance', 'Eye', 1),
('H60.90',  'Unspecified otitis externa, unspecified ear', 'Ear', 1),
('H66.90',  'Otitis media, unspecified, unspecified ear', 'Ear', 1),
('H81.10',  'Benign paroxysmal vertigo, unspecified ear', 'Ear', 1),
('H91.90',  'Unspecified hearing loss, unspecified ear', 'Ear', 1),
('H92.09',  'Otalgia, unspecified ear', 'Ear', 1),
('G43.909', 'Migraine, unspecified, not intractable, without status migrainosus', 'Neuro', 1),
('G43.919', 'Migraine, unspecified, intractable, without status migrainosus', 'Neuro', 1),
('G44.209', 'Tension-type headache, unspecified, not intractable', 'Neuro', 1),
('G56.00',  'Carpal tunnel syndrome, unspecified upper limb', 'Neuro', 1),
('G62.9',   'Polyneuropathy, unspecified', 'Neuro', 1),
('G89.29',  'Other chronic pain', 'Neuro', 1),
('G89.4',   'Chronic pain syndrome', 'Neuro', 1),
('G93.3',   'Postviral fatigue syndrome', 'Neuro', 1),

-- ============================================================================
-- NEOPLASMS (common screening / known history)
-- ============================================================================
('C50.911', 'Malignant neoplasm of unspecified site of right female breast', 'Neoplasm', 1),
('C50.919', 'Malignant neoplasm of unspecified site of unspecified female breast', 'Neoplasm', 1),
('C61',     'Malignant neoplasm of prostate', 'Neoplasm', 1),
('C78.7',   'Secondary malignant neoplasm of liver and intrahepatic bile duct', 'Neoplasm', 1),
('D12.6',   'Benign neoplasm of colon, unspecified', 'Neoplasm', 1),
('D49.9',   'Neoplasm of unspecified behavior of unspecified site', 'Neoplasm', 1),

-- ============================================================================
-- ENCOUNTER / FACTORS (Z-codes)
-- ============================================================================
('Z00.00',  'Encounter for general adult medical examination without abnormal findings', 'Factors', 1),
('Z00.01',  'Encounter for general adult medical examination with abnormal findings', 'Factors', 1),
('Z01.30',  'Encounter for examination of blood pressure without abnormal findings', 'Factors', 1),
('Z01.31',  'Encounter for examination of blood pressure with abnormal findings', 'Factors', 1),
('Z01.411', 'Encounter for routine gynecological examination with abnormal findings', 'Factors', 1),
('Z01.419', 'Encounter for routine gynecological examination without abnormal findings', 'Factors', 1),
('Z11.3',   'Encounter for screening for infections with a predominantly sexual mode of transmission', 'Factors', 1),
('Z11.51',  'Encounter for screening for human papillomavirus (HPV)', 'Factors', 1),
('Z11.59',  'Encounter for screening for other viral diseases', 'Factors', 1),
('Z12.11',  'Encounter for screening for malignant neoplasm of colon', 'Factors', 1),
('Z12.12',  'Encounter for screening for malignant neoplasm of rectum', 'Factors', 1),
('Z12.31',  'Encounter for screening mammogram for malignant neoplasm of breast', 'Factors', 1),
('Z12.39',  'Encounter for other screening for malignant neoplasm of breast', 'Factors', 1),
('Z12.5',   'Encounter for screening for malignant neoplasm of prostate', 'Factors', 1),
('Z13.1',   'Encounter for screening for diabetes mellitus', 'Factors', 1),
('Z13.220', 'Encounter for screening for lipoid disorders', 'Factors', 1),
('Z13.31',  'Encounter for screening examination for depression', 'Factors', 1),
('Z13.39',  'Encounter for screening examination for other mental health and behavioral disorders', 'Factors', 1),
('Z13.6',   'Encounter for screening for cardiovascular disorders', 'Factors', 1),
('Z13.820', 'Encounter for screening for osteoporosis', 'Factors', 1),
('Z23',     'Encounter for immunization', 'Factors', 1),
('Z51.81',  'Encounter for therapeutic drug level monitoring', 'Factors', 1),
('Z68.30',  'Body mass index [BMI] 30.0-30.9, adult', 'Factors', 1),
('Z68.34',  'Body mass index [BMI] 34.0-34.9, adult', 'Factors', 1),
('Z68.35',  'Body mass index [BMI] 35.0-35.9, adult', 'Factors', 1),
('Z68.36',  'Body mass index [BMI] 36.0-36.9, adult', 'Factors', 1),
('Z68.41',  'Body mass index [BMI] 40.0-44.9, adult', 'Factors', 1),
('Z68.42',  'Body mass index [BMI] 45.0-49.9, adult', 'Factors', 1),
('Z71.3',   'Dietary counseling and surveillance', 'Factors', 1),
('Z71.41',  'Alcohol abuse counseling and surveillance of alcoholic', 'Factors', 1),
('Z71.6',   'Tobacco abuse counseling', 'Factors', 1),
('Z71.82',  'Exercise counseling', 'Factors', 1),
('Z71.89',  'Other specified counseling', 'Factors', 1),
('Z72.0',   'Tobacco use', 'Factors', 1),
('Z72.4',   'Inappropriate diet and eating habits', 'Factors', 1),
('Z72.820', 'Sleep deprivation', 'Factors', 1),
('Z79.01',  'Long term (current) use of anticoagulants', 'Factors', 1),
('Z79.02',  'Long term (current) use of antithrombotics/antiplatelets', 'Factors', 1),
('Z79.4',   'Long term (current) use of insulin', 'Factors', 1),
('Z79.51',  'Long term (current) use of inhaled steroids', 'Factors', 1),
('Z79.52',  'Long term (current) use of systemic steroids', 'Factors', 1),
('Z79.811', 'Long term (current) use of selective estrogen receptor modulators (SERMs)', 'Factors', 1),
('Z79.82',  'Long term (current) use of aspirin', 'Factors', 1),
('Z79.84',  'Long term (current) use of oral hypoglycemic drugs', 'Factors', 1),
('Z79.890', 'Hormone replacement therapy', 'Factors', 1),
('Z79.891', 'Long term (current) use of opiate analgesic', 'Factors', 1),
('Z79.899', 'Other long term (current) drug therapy', 'Factors', 1),
('Z85.3',   'Personal history of malignant neoplasm of breast', 'Factors', 1),
('Z85.46',  'Personal history of malignant neoplasm of prostate', 'Factors', 1),
('Z86.39',  'Personal history of other endocrine, nutritional and metabolic disease', 'Factors', 1),
('Z86.71',  'Personal history of venous thrombosis and embolism', 'Factors', 1),
('Z86.73',  'Personal history of transient ischemic attack (TIA), and cerebral infarction without residual deficits', 'Factors', 1),
('Z87.11',  'Personal history of peptic ulcer disease', 'Factors', 1),
('Z87.19',  'Personal history of other diseases of the digestive system', 'Factors', 1),
('Z87.310', 'Personal history of (healed) osteoporosis fracture', 'Factors', 1),
('Z87.39',  'Personal history of other diseases of the musculoskeletal system and connective tissue', 'Factors', 1),
('Z87.74',  'Personal history of (corrected) congenital malformations of genitourinary system', 'Factors', 1),
('Z87.891', 'Personal history of nicotine dependence', 'Factors', 1),
('Z88.0',   'Allergy status to penicillin', 'Factors', 1),
('Z88.1',   'Allergy status to other antibiotic agents', 'Factors', 1),
('Z88.8',   'Allergy status to other drugs, medicaments and biological substances', 'Factors', 1),
('Z91.041', 'Radiographic dye allergy status', 'Factors', 1),
('Z91.19',  'Patient''s noncompliance with other medical treatment and regimen', 'Factors', 1),
('Z91.81',  'History of falling', 'Factors', 1);

PRINT 'Seed_ICDCodes_IM: rows inserted.';

END
ELSE
BEGIN
    PRINT 'Seed_ICDCodes_IM: sentinel code E11.65 already present — skipping insert.';
END
